### ISSUE TITLE
No Error Handling

### ISSUE THREAD

**Issue by msrd0** [matekeller/MateMateMoodlePlugin#1]
This plugin does not have error handling (at least for login failures) but instead just freezes the moodle page.

**Comment by Gameheld** [comment]
by doing which action did you get a freeze?

**Comment by Gameheld** [comment]
I can't reproduce it for the login dialog.

**Comment by msrd0** [comment]
Login with incorrect username

**Comment by Gameheld** [comment]
> Login with incorrect username

I only get a short 1-second freeze. Is this what you mean?

**Comment by msrd0** [comment]
No freeze was at least a minute. Reloadind fixed until next login failure.
